# Generated by Django 2.2.6 on 2019-10-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=25, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('ssl', models.BooleanField(default=False)),
            ],
        ),
    ]
