# Generated by Django 2.2.6 on 2019-10-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmodel',
            name='search_term',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='domainmodel',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
