# Generated by Django 2.2.6 on 2019-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dse', '0002_auto_20191029_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmodel',
            name='url',
            field=models.URLField(),
        ),
    ]
