# Generated by Django 2.2.6 on 2019-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dse', '0004_domainmodel_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
