# Generated by Django 2.2.6 on 2019-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dse', '0005_auto_20191029_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmodel',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
